apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: chartmuseum
spec:
  rules:
  - host: chartmuseum{{ .Values.cluster.namespaceSubDomain }}{{ .Values.cluster.domain }}
    http:
      paths:
      - backend:
          serviceName: jenkins-x-chartmuseum
          servicePort: 8080