apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-secret: jx-basic-auth
    nginx.ingress.kubernetes.io/auth-type: basic
  name: deck
spec:
  rules:
  - host: deck{{ .Values.cluster.namespaceSubDomain }}{{ .Values.cluster.domain }}
    http:
      paths:
      - backend:
          serviceName: deck
          servicePort: 80
{{- if .Values.cluster.tls }}
  tls:
  - hosts:
    - deck{{ .Values.cluster.namespaceSubDomain }}{{ .Values.cluster.domain }}
    secretName: "tls-{{ .Values.cluster.domain | replace "." "-" }}"
{{- end }}