apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hook
  namespace: jx
spec:
  rules:
  - host: hook{{ .Values.cluster.namespaceSubDomain }}{{ .Values.cluster.domain }}
    http:
      paths:
      - backend:
          serviceName: hook
          servicePort: 80