{{- if .Values.monocular.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: monocular
spec:
  rules:
  - host: monocular{{ .Values.cluster.namespaceSubDomain }}{{ .Values.cluster.domain }}
    http:
      paths:
      - backend:
          serviceName: jenkins-x-monocular-api
          servicePort: 80
        path: /api/
      - backend:
          serviceName: jenkins-x-monocular-ui
          servicePort: 80
        path: /
{{- end }}