apiVersion: v1
data:
  clusterName: {{ .Values.cluster.name | quote }}
  jx-install-version: -dev+548a93a-dev+4160558d5
  kubeProvider: gke
  projectID: {{ .Values.cluster.projectID | quote }}
  region: ""
  server: {{ .Values.cluster.serverUrl | quote }}
  zone: {{ .Values.cluster.zone | quote }}
kind: ConfigMap
metadata:
  name: jx-install-config
