apiVersion: jenkins.io/v1
kind: Environment
metadata:
  name: staging
spec:
  kind: Permanent
  label: Staging
  namespace: {{ .Values.cluster.namespace | default "jx" }}-staging
  order: 100
  previewGitInfo:
    user: {}
  promotionStrategy: Auto
  source:
    ref: master
    url: {{ .Values.gitops.staging.gitUrl }}
  teamSettings: {}
