enabled: {{ .Requirements.ingress.externalDNS }}
sources:
- ingress
provider: google
google:
  serviceAccount: external-dns-gcp-sa
rbac:
  create: "true"
domainFilters:
- "{{ .Requirements.ingress.domain }}"