enabled: {{ .Requirements.ingress.externalDNS }}
sources:
- ingress
provider: google
google:
  serviceAccount: external-dns
rbac:
  create: "true"
domainFilters:
- "{{ .Requirements.ingress.domain }}"