hmacToken: "{{ .Parameters.prow.hmacToken }}"
oauthToken: "{{ .Parameters.pipelineUser.github.token }}"
user: "{{ .Parameters.pipelineUser.github.username }}"

buildnum:
  enabled: false
pipelinerunner:
  enabled: "true"
  # image:
  #   repository: rawlingsj80/builder-maven
  #   tag: wip80
tillerNamespace: ""

sinker:
  replicaCount: 0
