apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  name: cb-kubecd-environment-jstrachan-ad1-production
spec:
  description: the git repository for the Production environment
  org: cb-kubecd
  provider: https://github.com
  providerName: github
  repo: environment-jstrachan-ad1-production
  scheduler:
    kind: Scheduler
    name: env-scheduler
