apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  name: jstrachan-nodey110
spec:
  description: Imported application for jstrachan/nodey110
  org: jstrachan
  provider: https://github.com
  providerName: github
  repo: nodey110
  scheduler:
    kind: ""
    name: ""
