adminUser:
  password: local:jstrachan-ofo2/adminUser:password
  username: admin
enableDocker: false
gitProvider: github
gpg: {}
pipelineUser:
  github:
    host: github.com
    token: local:jstrachan-ofo2/pipelineUser-github:token
    username: jenkins-x-bot-test
prow:
  hmacToken: local:jstrachan-ofo2/prow:hmacToken
