dependencies:
- alias: tekton
  name: tekton
  repository: http://chartmuseum.jenkins-x.io
  version: 0.0.39
- alias: prow
  name: prow
  repository: http://chartmuseum.jenkins-x.io
  version: 0.0.849
- name: jenkins-x-platform
  repository: http://chartmuseum.jenkins-x.io
  version: 2.0.718
#- condition: chartmuseum.enabled
#  name: chartmuseum
#  repository: http://chartmuseum.jenkins-x.io
#  version: 1.1.4