dependencies:
- alias: tekton
  name: tekton
  repository: http://chartmuseum.jenkins-x.io
  version: 0.0.41
- condition: prow.enabled
  alias: prow
  name: prow
  repository: http://chartmuseum.jenkins-x.io
  version: 0.0.960
- condition: lighthouse.enabled
  alias: lighthouse
  name: lighthouse
  repository: http://chartmuseum.jenkins-x.io
  version: 0.0.53
- name: jenkins-x-platform
  repository: http://chartmuseum.jenkins-x.io
  version:  2.0.872
- condition: external-dns.enabled
  name: external-dns
  repository: https://charts.bitnami.com/bitnami
  version: 1.5.2
#- condition: chartmuseum.enabled
#  name: chartmuseum
#  repository: http://chartmuseum.jenkins-x.io
#  version: 1.1.4